# Generated by Django 5.2.6 on 2025-09-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='product_videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sale', 'On Sale'), ('sold', 'Sold')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
