# Generated by Django 5.2.6 on 2025-09-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image1', models.ImageField(upload_to='gaming_accessories/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='gaming_accessories/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='gaming_accessories/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sale', 'On Sale'), ('sold', 'Sold')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
