# Generated by Django 5.2.6 on 2025-09-21 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_review_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('total_prize_pool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('individual_entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('team_entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rules', models.TextField()),
                ('structure', models.TextField()),
                ('time_limit', models.PositiveIntegerField(help_text='Time limit in minutes')),
                ('allowed_weapons', models.TextField(help_text='Comma-separated list of allowed weapons')),
                ('restricted_weapons', models.TextField(help_text='Comma-separated list of restricted weapons')),
                ('allowed_maps', models.TextField(help_text='Comma-separated list of allowed maps')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrizeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='accounts.tournament')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
